# yaml-language-server: $schema=https://static.codemagic.io/codemagic-schema.json
workflows:
  ci:
    name: CI
    instance_type: mac_mini_m1
    max_build_duration: 15
    environment:
      flutter: 3.7.9
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Lint
        script: flutter analyze
      - name: Unit tests and widget tests
        script: flutter test