# yaml-language-server: $schema=https://static.codemagic.io/codemagic-schema.json
workflows:
  ci:
    name: CI
    instance_type: mac_mini_m1
    max_build_duration: 15
    environment:
      flutter: 3.7.9
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      cancel_previous_builds: false
    scripts:
      - name: Lint
        script: |
          flutter analyze
          flutter pub run dart_code_metrics:metrics analyze lib --verbose
      - name: Unit tests and widget tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/tests.json
        test_report: test-results/tests.json
      - name: Integration tests
        script: |
          mkdir -p test-results
          flutter emulators --launch apple_ios_simulator
          flutter -d iPhone test --machine > test-results/flutter.json integration_test
          xcrun simctl shutdown all
          xcrun simctl list
          TEST_DEVICE=$(xcrun simctl create test-device com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-15-0)
          xcrun simctl boot $TEST_DEVICE
          flutter -d $TEST_DEVICE test --verbose