# yaml-language-server: $schema=https://static.codemagic.io/codemagic-schema.json
workflows:
  ci:
    name: CI
    instance_type: mac_mini_m1
    max_build_duration: 15
    environment:
      flutter: 3.7.9
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Lint
        script: flutter analyze
      - name: Unit tests and widget tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Integration tests
        script: |
          mkdir -p test-results
          flutter config --enable-web
          flutter emulators --launch emulator &
          adb wait-for-device
          flutter -d emulator-5554 test --machine > test-results/flutter.json integration_test
        test_report: test-results/flutter.json
# for iOS, execute the commands below
# flutter emulators --launch apple_ios_simulator
# flutter -d iPhone test integration_test
