name: main

on:
  push:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch: ~

jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
          cache: true
      - name: Install
        run: flutter pub get
      - name: Lint
        run: flutter analyze
      - name: Test
        run: |
          flutter test test/
          flutter config --enable-web
          flutter devices
          flutter emulators --launch emulator-5554 &
          adb wait-for-device
          flutter -d emulator-5554 test --machine > test-results/flutter.json integration_test
